apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mobot.fullname" . }}
  labels:
{{ include "mobot.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mobot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mobot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # ports:
          #   - name: http
          #     containerPort: 80
          #     protocol: TCP
          # livenessProbe:
          #   exec:
          #     command:
          #       - pgrep -lf slackbot
          #     initialDelaySeconds: 5
          #     periodSeconds: 5
          # readinessProbe:
          #   exec:
          #     command:
          #       - pgrep -lf slackbot
          #     initialDelaySeconds: 5
          #     periodSeconds: 5
          env:
            - name: SLACK_API_TOKEN
              value: xoxb-3761985377-713549102387-qniODs02AEVRQyqkwru3xqe6
            - name: LOG_LEVEL
              value: DEBUG
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
